version: "3"
services:
  node:
    build: ./forum-web
    ports:
      - "8440:3000"
    restart: unless-stopped

  
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - PASSWORD=${CODE_PASSWORD}
      - PROXY_DOMAIN=code-server.pietschcloud.de
      - DEFAULT_WORKSPACE=/config/workspace 
    volumes:
      - config:/config
    ports:
      - 8443:8443
    restart: unless-stopped
volumes:
  config: